name: CI/CD Pipeline

# Trigger pipeline on push or PR to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build
        run: npm run build

      # 5. Run tests
      - name: Test
        run: npm test

      # 6. Deploy (simulated)
      - name: Deploy
        run: |
          echo "Deployment step"
          echo "This is where the app would be deployed to a server"
